Repository WildCodeSchool/orleans-0218-metiersnumerique, pull requests merged in 2018-04, with the labels that each got.

#12 US1 -S1-Navbar
  README.md
  public/assets/css/global.css
  public/assets/css/navbar.css
  public/assets/css/styles.css
  public/assets/images/logo_orange_pastille.png
  simple-mvc.sql
  src/View/Item/_form.html.twig
  src/View/Item/add.html.twig
  src/View/Item/edit.html.twig
  src/View/Item/index.html.twig
  src/View/Item/show.html.twig
  src/View/layout.html.twig
  src/View/navbar.html.twig
Labels: Reviewed by PO

#13 US3-S1-Footer
  public/assets/css/footer.css
  public/assets/images/footer/facebook.png
  public/assets/images/footer/facebook_gris.png
  public/assets/images/footer/github.png
  public/assets/images/footer/github_gris.png
  public/assets/images/footer/instagram.png
  public/assets/images/footer/instagram_gris.png
  public/assets/images/footer/linkedin.png
  public/assets/images/footer/linkedin_gris.png
  public/assets/images/footer/logo_wild.png
  public/assets/images/footer/twitter.png
  public/assets/images/footer/twitter_gris.png
  public/assets/images/footer/youtube.png
  public/assets/images/footer/youtube_gris.png
  src/View/footer.html.twig
Labels: Reviewed by PO

#35 Intégration de la page d'accueil avec la navbar et le footer
  app/routing.php
  public/assets/css/footer.css
  public/assets/css/global.css
  public/assets/css/index.css
  src/Controller/IndexController.php
  src/View/footer.html.twig
  src/View/index.html.twig
  src/View/layout.html.twig
  src/View/navbar.html.twig
Labels: Reviewed by PO

#36 Intégration de la page d'accueil
  README.md
  app/routing.php
  public/assets/css/footer.css
  public/assets/css/global.css
  public/assets/css/index.css
  public/assets/css/navbar.css
  public/assets/css/styles.css
  public/assets/images/footer/facebook.png
  public/assets/images/footer/facebook_gris.png
  public/assets/images/footer/github.png
  public/assets/images/footer/github_gris.png
  public/assets/images/footer/instagram.png
  public/assets/images/footer/instagram_gris.png
  public/assets/images/footer/linkedin.png
  public/assets/images/footer/linkedin_gris.png
  public/assets/images/footer/logo_wild.png
  public/assets/images/footer/twitter.png
  public/assets/images/footer/twitter_gris.png
  public/assets/images/footer/youtube.png
  public/assets/images/footer/youtube_gris.png
  public/assets/images/logo_orange_pastille.png
  simple-mvc.sql
  src/Controller/IndexController.php
  src/View/Item/_form.html.twig
  src/View/Item/add.html.twig
  src/View/Item/edit.html.twig
  src/View/Item/index.html.twig
  src/View/Item/show.html.twig
  src/View/footer.html.twig
  src/View/index.html.twig
  src/View/layout.html.twig
  src/View/navbar.html.twig
Labels: Reviewed by PO

#37 Us9 s3 user add comment
  app/routing.php
  public/assets/css/form.css
  public/assets/css/global.css
  public/assets/css/navbar.css
  src/Controller/CommentController.php
  src/Controller/ItemController.php
  src/Model/AbstractManager.php
  src/Model/Comment.php
  src/Model/CommentManager.php
  src/Model/Item.php
  src/View/comment.html.twig
Labels: Change requested, Correction done

#42 affichage carte metiers
  app/db.php.dist
  app/routing.php
  public/assets/css/bandeau.css
  public/assets/css/themes.css
  public/assets/images/icon-comment.png
  src/Controller/JobController.php
  src/Model/Job.php
  src/Model/JobManager.php
  src/Model/Theme.php
  src/Model/ThemeManager.php
  src/View/Jobs/jobs.html.twig
  src/View/bandeau.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#38 US11-S3-Comments
  app/routing.php
  public/assets/css/admin/comment.css
  public/assets/css/global.css
  src/Controller/CommentController.php
  src/Model/AbstractManager.php
  src/Model/Comment.php
  src/Model/CommentManager.php
  src/Model/Format.php
  src/Model/Job.php
  src/Model/JobManager.php
  src/View/Admin/comment.html.twig
Labels: Correction done, Reviewed by PO

#43 fix container
  src/View/job.html.twig
Labels: Reviewed by PO

#45 Fix dev
  app/routing.php
  src/View/Jobs/jobs.html.twig
  src/View/index.html.twig
  src/View/job.html.twig
Labels: Reviewed by PO

#57 Us12 validation commentaires
  app/routing.php
  public/assets/css/admin/view_comment.css
  public/assets/images/default_avatar.jpg
  src/Controller/CommentController.php
  src/Model/AbstractManager.php
  src/Model/CommentManager.php
  src/View/Admin/view_comment.html.twig
Labels: Reviewed by PO

#59 Ajout de la fonctionnalité de validation des commentaires.
  app/routing.php
  public/assets/css/admin/view_comment.css
  public/assets/images/default_avatar.jpg
  src/Controller/CommentController.php
  src/Model/AbstractManager.php
  src/Model/CommentManager.php
  src/View/Admin/view_comment.html.twig
Labels: Reviewed by PO

#58 Us13 pagination commentaires
  app/config.php
  app/routing.php
  public/assets/css/admin/comment.css
  src/Controller/CommentController.php
  src/Model/AbstractManager.php
  src/Model/CommentManager.php
  src/Model/Paginator.php
  src/View/Admin/comment.html.twig
Labels: Reviewed by PO

#60 Dev to Master
  app/config.php
  app/routing.php
  public/assets/css/admin/comment.css
  src/Controller/CommentController.php
  src/Model/AbstractManager.php
  src/Model/CommentManager.php
  src/Model/Paginator.php
  src/View/Admin/comment.html.twig
Labels: Reviewed by PO

#61 récupération des 3 premiers commentaires dans bdd et affichage sur fiche métier
  public/assets/css/job.css
  public/assets/images/quotes.png
  src/Controller/JobController.php
  src/Model/CommentManager.php
  src/View/job.html.twig
Labels: Reviewed by PO

#64 affichage nombre de commentaire
  src/Controller/CommentController.php
  src/Controller/JobController.php
  src/Model/CommentManager.php
  src/View/Jobs/jobs.html.twig
Labels: Reviewed by PO

#62 Us8 s4 Affichage de l'image ou de la vidéo dans la fiche métier
  public/assets/css/global.css
  public/assets/css/job.css
  src/View/job.html.twig
Labels: Correction done, Reviewed by PO

#65 Us7 s4 fixe css carte metier
  public/assets/css/bandeau.css
  public/assets/css/themes.css
  src/View/Jobs/jobs.html.twig
  src/View/bandeau.html.twig
Labels: Reviewed by PO

#63 Ajout d'un nouveau thème.
  app/routing.php
  public/assets/css/admin/themes-jobs.css
  public/index.php
  src/Controller/AdminController.php
  src/Controller/ThemeController.php
  src/Model/AbstractManager.php
  src/View/Admin/themes-jobs.html.twig
  src/View/layout.html.twig
Labels: Correction done, Reviewed by PO

#67 Us12 validation commentaires
  public/assets/css/form.css
  public/assets/css/global.css
  src/Controller/CommentController.php
  src/Model/CleanInput.php
  src/Validator/AbstractValidator.php
  src/Validator/Comment.php
  src/Validator/EmailValidator.php
  src/Validator/MaxLengthValidator.php
  src/Validator/NotEmptyValidator.php
  src/Validator/ValidatorInterface.php
  src/View/comment.html.twig
Labels: Conflict, Correction done, Reviewed by PO

#69 Dev to master
  app/routing.php
  public/assets/css/admin/themes-jobs.css
  public/assets/css/bandeau.css
  public/assets/css/form.css
  public/assets/css/global.css
  public/assets/css/job.css
  public/assets/css/themes.css
  public/assets/images/quotes.png
  public/index.php
  src/Controller/AdminController.php
  src/Controller/CommentController.php
  src/Controller/JobController.php
  src/Controller/ThemeController.php
  src/Model/AbstractManager.php
  src/Model/CleanInput.php
  src/Model/CommentManager.php
  src/Validator/AbstractValidator.php
  src/Validator/Comment.php
  src/Validator/EmailValidator.php
  src/Validator/MaxLengthValidator.php
  src/Validator/NotEmptyValidator.php
  src/Validator/ValidatorInterface.php
  src/View/Admin/themes-jobs.html.twig
  src/View/Jobs/jobs.html.twig
  src/View/bandeau.html.twig
  src/View/comment.html.twig
  src/View/job.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#70 Fix bug extension image par défaut.
  src/Controller/CommentController.php
Labels: Reviewed by PO

#71 Dev to master
  src/Controller/CommentController.php
Labels: Reviewed by PO

#72 Bouton commentaires
  public/assets/css/job.css
  src/View/job.html.twig
Labels: Reviewed by PO

#73 modif navbar mobile
  public/assets/css/global.css
  public/assets/css/navbar.css
  public/assets/css/themes.css
  src/View/Jobs/jobs.html.twig
  src/View/navbar.html.twig
Labels: Reviewed by PO

#74 Dev to master
  public/assets/css/global.css
  public/assets/css/job.css
  public/assets/css/navbar.css
  public/assets/css/themes.css
  src/View/Jobs/jobs.html.twig
  src/View/job.html.twig
  src/View/navbar.html.twig
Labels: Reviewed by PO

#89 Us24 s5 ajout lien logo accueil
  src/View/navbar.html.twig
Labels: Reviewed by PO

#90 Us10 s4 commentaires responsive
  public/assets/css/job.css
  src/View/job.html.twig
Labels: Reviewed by PO

#91 Us14 s5 accueil
  public/assets/css/index.css
  public/assets/images/server.jpg
  src/View/index.html.twig
Labels: Reviewed by PO

#92 Us15 navbar admin
  public/assets/css/admin/navbar.css
  public/assets/css/bandeau.css
  public/assets/css/global.css
  src/Controller/CommentController.php
  src/View/Admin/comment.html.twig
  src/View/Admin/navbar.html.twig
  src/View/Admin/themes-jobs.html.twig
  src/View/Admin/view-comment.html.twig
Labels: Reviewed by PO

#94 Us 22 tri des commentaires par like
  app/routing.php
  public/assets/css/job.css
  src/Controller/CommentController.php
  src/Model/CommentManager.php
  src/View/job.html.twig
Labels: Reviewed by PO

#97 Us25 ajout d'une légende sur la page admin pour la gestion des commentaires
  public/assets/css/admin/comment.css
  src/View/Admin/comment.html.twig
Labels: Reviewed by PO

#99 Us 20 s 5 suppression thème
  app/routing.php
  public/assets/css/admin/themes-jobs.css
  public/assets/js/confirm.js
  src/Controller/AdminController.php
  src/Controller/ThemeController.php
  src/Model/AbstractManager.php
  src/Model/JobManager.php
  src/View/Admin/themes-jobs.html.twig
Labels: Correction done, Reviewed by PO

#100 US 18 Modification des thèmes avec gestion des erreurs
  app/routing.php
  src/Controller/ThemeController.php
  src/View/Admin/modification-theme.html.twig
Labels: Reviewed by PO

#101 Us 16 s5 affichage dynamique commentaires
  app/routing.php
  public/assets/css/job.css
  public/assets/images/avatar/image5adf562638bad.png
  public/assets/js/load-comments.js
  src/Controller/AdminController.php
  src/Controller/CommentController.php
  src/Controller/ThemeController.php
  src/Model/CommentManager.php
  src/Model/JobManager.php
  src/View/Admin/modification-theme.html.twig
  src/View/Admin/themes-jobs.html.twig
  src/View/job.html.twig
  src/View/load-comment.html.twig
Labels: Correction done, Reviewed by PO

#106 fix modification des col de la légende des commentaires
  src/View/Admin/comment.html.twig
Labels: Reviewed by PO

#107 fix return of count nb job by theme id
  src/Model/JobManager.php
Labels: Reviewed by PO

#108 Ajout du validateur dans la méthode addTheme.
  src/Controller/ThemeController.php
Labels: Correction done, Reviewed by PO

#110 fix changement des questions de l'administrateur
  src/View/Admin/view-comment.html.twig
Labels: Reviewed by PO

#109 suppression de l'affichage des commentaires non validés
  src/Model/CommentManager.php
  src/View/Jobs/jobs.html.twig
Labels: Correction done, Reviewed by PO

#113 fix add row every line of comments
  public/assets/images/avatar/image5ae081797cadb.jpg
  src/View/load-comment.html.twig
Labels: Reviewed by PO

#114 Réalignement des boutons dans la vue métier.
  src/View/job.html.twig
Labels: Reviewed by PO

#115 fix erreur add theme
  src/View/Admin/themes-jobs.html.twig
Labels: Reviewed by PO

#112 affichage avatar en js et bouton retour
  public/assets/css/form.css
  public/assets/images/avatar/image5ae0808b2e711.gif
  public/assets/js/comment.js
  src/View/comment.html.twig
Labels: Correction done, Reviewed by PO

#118 Admin - Suppression des commentaires
  app/routing.php
  public/assets/css/admin/comment.css
  public/assets/css/admin/themes-jobs.css
  public/assets/css/admin/view-comment.css
  src/Controller/CommentController.php
  src/View/Admin/view-comment.html.twig
Labels: Reviewed by PO

#119 fix
  public/assets/images/avatar/image5ae099edcedec.gif
  public/assets/images/avatar/image5ae0aa560f876.png
  src/View/Admin/comment.html.twig
  src/View/Admin/view-comment.html.twig
Labels: Reviewed by PO

#122 Fix bug pagination
  public/assets/images/avatar/image5ae188a06b41c.jpg
  public/assets/images/avatar/image5ae19d5c053ee.jpg
  src/Model/Paginator.php
  src/View/Admin/comment.html.twig
Labels: Reviewed by PO

#123 fix fermeture de row lors du chargement des commentaires
  src/View/load-comment.html.twig
Labels: Reviewed by PO

#124 fix col vidéo accueil et taille du texte
  public/assets/css/global.css
  public/assets/css/index.css
  src/View/index.html.twig
Labels: Reviewed by PO

#127 redimensionnement avatar
  public/assets/css/job.css
Labels: Reviewed by PO

#128 Us19 s5 modification fiche metier
  .gitignore
  app/routing.php
  public/assets/js/update-job.js
  src/Controller/JobController.php
  src/View/Admin/update-job.html.twig
Labels: Reviewed by PO

#129 fixUserAvatar
  src/View/load-comment.html.twig
Labels: Reviewed by PO

#130 fix img circle avatar
  public/assets/css/form.css
  src/View/comment.html.twig
Labels: Correction done, Reviewed by PO

#120 suppression fiche metier
  app/routing.php
  src/Controller/AdminController.php
  src/Controller/JobController.php
  src/Model/AbstractManager.php
  src/View/Admin/themes-jobs.html.twig
Labels: Correction done, Reviewed by PO

#131 Fix add job banner and navbar
  public/assets/css/global.css
  src/View/Admin/add-job.html.twig
Labels: Reviewed by PO

#132 ajout des push array et augmentation du maxLength validateur sur la d…
  src/Controller/JobController.php
Labels: Reviewed by PO

#134 fix
  src/Controller/JobController.php
  src/View/Admin/add-job.html.twig
  src/View/Admin/update-job.html.twig
Labels: Reviewed by PO

#135 suppression du texte et modifs sur le logo
  public/assets/css/footer.css
  public/assets/images/avatar/image5ae2d3b5888df.jpg
  public/assets/images/avatar/image5ae2d92f2379c.jpg
  public/assets/images/avatar/image5ae2d95a06f47.jpeg
  src/View/footer.html.twig
Labels: Reviewed by PO

#136 add nb jobs by theme on pills for user
  src/Controller/JobController.php
  src/View/Jobs/jobs.html.twig
Labels: Reviewed by PO

#138 Ajout du control sur le bouton like des commentaires.
  public/assets/js/add-like.js
  src/Controller/CommentController.php
  src/View/load-comment.html.twig
Labels: Reviewed by PO

#139 Fix update
  src/Controller/JobController.php
  src/Model/AbstractManager.php
  src/View/Admin/add-job.html.twig
  src/View/Admin/update-job.html.twig
Labels: Reviewed by PO

#140 Modification du systèm de like pour pouvoir liker plusieurs commentai…
  public/assets/js/add-like.js
  src/Controller/CommentController.php
Labels: Reviewed by PO

#141 Affichage du nombre de fiche métier sous forme de badge dans les pills.
  public/assets/css/themes.css
  src/View/Jobs/jobs.html.twig
Labels: Reviewed by PO

#142 passage du logo wild avec les logos réseaux sociaux
  public/assets/css/footer.css
  public/assets/images/avatar/image5ae30e1c7ee00.jpg
  src/View/footer.html.twig
Labels: Reviewed by PO

#143 update job works
  src/Controller/JobController.php
  src/Model/Upload.php
Labels: Correction done, Reviewed by PO

#144 fix taille résumé et description, ajout de / dans la vue pour affiche…
  src/Controller/JobController.php
  src/View/Admin/add-job.html.twig
  src/View/Admin/update-job.html.twig
  src/View/job.html.twig
Labels: Reviewed by PO

#146 add default image pour la fiche métier
  .gitignore
  public/assets/images/image-metiers/default_image.jpg
Labels: Reviewed by PO

#147 suppression des commentaires avec avatar lors de suppression de fiche
  public/assets/images/avatar/image5ae099edcedec.gif
  public/assets/images/avatar/image5ae0aa560f876.png
  public/assets/images/avatar/image5ae188a06b41c.jpg
  public/assets/images/avatar/image5ae19d5c053ee.jpg
  public/assets/images/avatar/image5ae2d3b5888df.jpg
  public/assets/images/avatar/image5ae2d65496161.png
  public/assets/images/avatar/image5ae2d92f2379c.jpg
  public/assets/images/avatar/image5ae2d95a06f47.jpeg
  public/assets/images/avatar/image5ae2dba2cfd23.gif
  public/assets/images/avatar/image5ae30e1c7ee00.jpg
  src/Controller/JobController.php
  src/Controller/ThemeController.php
  src/Model/CommentManager.php
Labels: Correction done, Reviewed by PO

#145 ajout d'une légende champs obligatoires dans les formulaires
  public/assets/css/form.css
  src/View/Admin/add-job.html.twig
  src/View/Admin/update-job.html.twig
  src/View/comment.html.twig
Labels: Reviewed by PO
